### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by omurad** [moneromooo-monero/monero-update#1]
I would love to test this on my Windows 10 machine but not exactly sure how to go about building it.

Adding build instruction for Windows/macOS/Linux would be super helpful for myself and others looking to test this.

**Comment by moneromooo-monero** [comment]
Standard cmake:

mkdir build; cd build; cmake ..; make; cd ..

I'll add that to the README.

On Windows, note that it'll crash unless you're using a recent master of gpgme (the 0.13.1 that ships in msys2 is busted).
